web:
  build: .
  dockerfile: conf/Dockerfile.web
  ports:
    - "8000:80"
  links:
    - db
  volumes:
    - .:/var/www/html/

db:
  build: ./conf
  dockerfile: Dockerfile.db
  volumes:
    - ./mysql:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: wlm
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: password
